### ISSUE TITLE
Unable to catch the error and watch stops while using jslint

### ISSUE THREAD

**Issue by mythical-programmer** [benquarmby/gulp-byo-jslint#1]
I have tried to catch the error thrown from gulp-byo-jslint, but not working. I used .on("error", ..,) , plumber() etc. None of the solution work.

The watch is getting broken once there is error. I want to avoid it. How to do that ?

**Comment by benquarmby** [comment]
Sounds like I've made an incorrect assumption about how the [event-stream](https://www.npmjs.com/package/event-stream) library handles exceptions.

This is a bug. I'll look into it soon.

**Comment by benquarmby** [comment]
OK, not a bug per-se, but I'll leave the label. This plugin deliberately logs instead of throwing exceptions so that all violations are enumerated to the console in a typical command line scenario. It then throws a single exception at the very end to fail the gulp task. But this is within an event handler where it wont be wrapped in an `error` event.

I think the best course of action would be to make the plugin's error handling configurable:
- All
  Throw each warning instead of logging
- One (default)
  Log each warning, throw at the end
- None
  Log each warning, never throw

I'm guessing the last option would suit gulp watch scenarios best.

**Comment by benquarmby** [comment]
The actual solution ended up much simpler. Set the new `noFail` flag when using with gulp watch. See the readme for an example.

**Comment by mythical-programmer** [comment]
Thanks. That helped.
 Exactly what I wanted.
